import { readFileSync, existsSync, writeFileSync, mkdirSync } from 'fs'
import { join, dirname } from 'path'
import { homedir } from 'os'

const CONFIG_DIR = join(homedir(), '.config', 'doto')
export const CONFIG_FILE = join(CONFIG_DIR, 'config.env')

function parseEnvFile(content) {
  const vars = {}
  for (const line of content.split('\n')) {
    const trimmed = line.trim()
    if (!trimmed || trimmed.startsWith('#')) continue
    const eqIdx = trimmed.indexOf('=')
    if (eqIdx === -1) continue
    const key = trimmed.slice(0, eqIdx).trim()
    const val = trimmed.slice(eqIdx + 1).trim()
    vars[key] = val
  }
  return vars
}

function setIfMissing(vars) {
  for (const [key, val] of Object.entries(vars)) {
    if (process.env[key] === undefined) process.env[key] = val
  }
}

// Walk up from cwd looking for a project .env; apply DOTO_ vars only
function loadProjectEnv() {
  let dir = process.cwd()
  while (true) {
    const candidate = join(dir, '.env')
    if (existsSync(candidate)) {
      try {
        const all = parseEnvFile(readFileSync(candidate, 'utf8'))
        const doto = Object.fromEntries(Object.entries(all).filter(([k]) => k.startsWith('DOTO_')))
        setIfMissing(doto)
      } catch {}
      return
    }
    const parent = dirname(dir)
    if (parent === dir) return
    dir = parent
  }
}

function loadGlobalConfig() {
  if (!existsSync(CONFIG_FILE)) return
  try {
    setIfMissing(parseEnvFile(readFileSync(CONFIG_FILE, 'utf8')))
  } catch {}
}

// Side effect on import: precedence = shell (already set) > project .env > global config
// setIfMissing ensures higher-priority sources are never overwritten
loadProjectEnv()
loadGlobalConfig()

export function configExists() {
  return existsSync(CONFIG_FILE)
}

export function readConfig() {
  if (!existsSync(CONFIG_FILE)) return {}
  try { return parseEnvFile(readFileSync(CONFIG_FILE, 'utf8')) } catch { return {} }
}

export function writeConfig(vars) {
  mkdirSync(CONFIG_DIR, { recursive: true })
  const lines = ['# doto global config', '# generated by doto setup', '']
  for (const [k, v] of Object.entries(vars)) lines.push(`${k}=${v}`)
  writeFileSync(CONFIG_FILE, lines.join('\n') + '\n')
}
